[tree-sitter-norg]
src.git = "https://github.com/nvim-neorg/tree-sitter-norg"
fetch.github = "nvim-neorg/tree-sitter-norg"

[tree-sitter-norg-meta]
src.git = "https://github.com/nvim-neorg/tree-sitter-norg-meta"
fetch.github = "nvim-neorg/tree-sitter-norg-meta"

[tree-sitter-norg-table]
src.git = "https://github.com/nvim-neorg/tree-sitter-norg-table"
fetch.github = "nvim-neorg/tree-sitter-norg-table"

[tree-sitter-vala]
src.git = "https://github.com/vala-lang/tree-sitter-vala"
fetch.github = "vala-lang/tree-sitter-vala"
